apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-svc
  labels:
    name: redis-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-svc
  template:
    metadata:
      labels:
        app: redis-svc
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
