apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rworker-rc
  labels:
    name: rdocker-hpc-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rworker
  template:
    metadata:
      labels:
        app: rworker
    spec:
      containers:
      - name: rdockerhpc-worker
        image: trcook/rdockerhpc_worker
